### ISSUE TITLE
Орфография

### ISSUE THREAD

**Issue by MikhailRyazanov** [deNULL/elections-2021#1]
Исправьте, пожалуйста, вот это недоразумение:
https://github.com/deNULL/elections-2021/blob/05020d2391838a3bb6793d0da8de0a4de3ed6821/js/main.js#L46
По правилам в данных случаях наращивается только одна буква окончания, т. е. должно быть `'-и места'` и `'-е места'`. (Неужели вам самому это «3-**ь**и» не режет глаз?)

**Comment by denull** [comment]
Поправил

**Comment by MikhailRyazanov** [comment]
Спасибо! И картинку на Habr-е, если не сложно. :–)

**Comment by denull** [comment]
Поправил картинку тоже, спасибо за замечание :)
